<?php

namespace Ecs\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeadTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadTypeRepository extends EntityRepository
{
}