security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    #role_hierarchy:
    #    ROLE_CSREP: ROLE_SALESREP
    #    ROLE_FLOORMAN: [ROLE_CSREP, ROLE_FLOORUSERMAN]
    #    ROLE_OPERATIONSMANAGER: [ROLE_FLOORMAN, ROLE_REPORTVIEWER]
    #    ROLE_ADMIN: [ROLE_FULLUSERMAN, ROLE_OPERATIONSMANAGER]
    #    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:  ^/
            form_login:
                provider: fos_userbundle
            logout:	true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN