customer:
    pattern:  /
    defaults: { _controller: "EcsCrmBundle:Customer:index" }

customer_register:
    pattern:  /register
    defaults: { _controller: "EcsCrmBundle:Customer:register" }

customer_show:
    pattern:  /{id}/show
    defaults: { _controller: "EcsCrmBundle:Customer:show" }

customer_new:
    pattern:  /new
    defaults: { _controller: "EcsCrmBundle:Customer:new" }

customer_create:
    pattern:  /create
    defaults: { _controller: "EcsCrmBundle:Customer:create" }
    requirements: { _method: post }

customer_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EcsCrmBundle:Customer:edit" }

customer_update:
    pattern:  /{id}/update
    defaults: { _controller: "EcsCrmBundle:Customer:update" }
    requirements: { _method: post }

customer_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EcsCrmBundle:Customer:delete" }
    requirements: { _method: post }

wizard_step1:
    pattern: /newclient
    defaults: { _controller: "EcsCrmBundle:SignupWizard:step1" }
    requirements: { _method: get|post }

wizard_step2:
    pattern: /step2/{id}
    defaults: { _controller: "EcsCrmBundle:SignupWizard:step2", id : null } }
    requirements: { _method: get|post }